### ISSUE TITLE
Cut keyboard shortcut (Command + x) does not work

### ISSUE THREAD

**Issue by reggi** [plibither8/markdown-new-tab#1]
Hey! Great extension. I just tried to cut text within the edit mode and it does not work.

**Comment by plibither8** [comment]
Hey! This is issue was certainly realised by me too but I kind of forgot about it, sorry :D. I know the solutions, I'll push changes and update the extension as soon as possible. Thanks!

**Comment by aslafy-z** [comment]
Have this been released? I still hit this bug

**Comment by plibither8** [comment]
Hi Zadkiel 👋,

Certainly the issue persists, I thought I fixed it with https://github.com/plibither8/markdown-new-tab/commit/1a728d5cccaa440667f8c209a3dff989603d1023. Thanks for pointing it out 😄.

I understand the issue now, the `else if (e.keyCode === 88)` condition should not be considered when `textarea` is displayed. I'd love it if you could create a PR that fixes the issue. In any case, I'll be working on this next week, until then you can try your hand at it 🙃.

**Comment by plibither8** [comment]
@aslafy-z Fixed the issue and released the updated package (v1.4.5)! I'll close the issue once I get confirmation from your side :+1:

**Comment by aslafy-z** [comment]
It work like a charm! Thanks
