### ISSUE TITLE
Feature Request: add Keyboard shortcut, checkbox check after saved

### ISSUE THREAD

**Issue by jung-han** [plibither8/markdown-new-tab#12]
Thx for your great chrome extension😄

I would like to propose a function to improve some of the inconvenience.
First, it is not possible to select and clear the checkbox after saving MarkDown.
And I can see the MarkDown reflection after saving, it would be convenient to have a shortcut.
Just saving, editing.

**Comment by plibither8** [comment]
Hi @jung-han 

> First, it is not possible to select and clear the checkbox after saving MarkDown.

For clearing checkboxes if a GUI-like "click-and-clear" is added, I feel that it might ruin the 'text editor' feel of the page. Moreover it feels incomplete if a GUI-like feature is added to only one part when it might be appropriate in other places as well (like creating tables etc.). Nevertheless if this need for this feature grows, I'll try my best to implement it.

> And I can see the MarkDown reflection after saving, it would be convenient to have a shortcut.
Just saving, editing.

If you are refering to keyboard shortcuts that save and edit the documents (and change views), they already exist :smile:! Here they are: <kbd>Ctrl</kbd> + <kbd>X</kbd> (or <kbd>Cmd</kbd> + <kbd>X</kbd> on Mac) to edit the text and <kbd>Ctrl</kbd> + <kbd>S</kbd> (or <kbd>Cmd</kbd> + <kbd>S</kbd> on Mac) to save the text.

There's a slight chance I might have misunderstood your second query though. Have I?

Thank you

**Comment by jung-han** [comment]
@plibither8 Oh. It's already existed🤪. Thank you for your kind answer.
