### ISSUE TITLE
Like it and hope it become an isolated web app or native app

### ISSUE THREAD

**Issue by ImHUan** [plibither8/markdown-new-tab#20]
Hi guys! I like this extension and its feature & UI. BUT for me it's weird to use a browser tab to write notes while I m using Evernote or Bear as my primary note-taking tool. And it's not convenient for smart phone or office pc which can't install new app to use it.

Anyway, thanks so much you create such a good app and best wishes to you and your team!  👍 :)

**Comment by plibither8** [comment]
Hey! I understand where you're coming from and possibly this is one of the fields where the popular cross-platform apps beats MDNT, so I don't know if there is a possibility of having native web app for this WITH your notes being synced (unless I use another method to sync notes, such as a GitHub Gist maybe(?)). Let's hope Chrome allows for extensions on mobile devices soon 😄! Thank you for your kind words!
