### ISSUE TITLE
All links have target=_blank set

### ISSUE THREAD

**Issue by johannes87** [plibither8/markdown-new-tab#24]
This is a user experience wish

However, I'd prefer to have that attribute not set, for the following reason:

When I click on a link, I have left over the "New Tab" tab, which I don't need anymore. So I need to go back to clean up an non-needed tab, if I want to keep my tab list clean.

After all, I can always get to that page again simply by pressing C+T

**Comment by plibither8** [comment]
Hey 👋,

Now that I think about it, you're right. I remember in the initial development of this project I kept the `target=_blank` for debugging purposes. It's best if it is removed now.

I'll not be able to work actively on this project anytime soon this week, so if you can create a PR of the same, I'll be happy to review and merge it 👍.

Thanks,
Mihir

**Comment by johannes87** [comment]
@plibither8 any news on this?

**Comment by plibither8** [comment]
Hi @johannes87, super sorry about the delay, I didn't get time to use GitHub this entire month. I'll merge the PR right now, and upload the updated version on the Chrome Webstore - I'll notify you once I do.

Thanks a lot for your patience, sorry again :grimacing:!

**Comment by plibither8** [comment]
Hey, I've just published the updated version on the Webstore. The changes will take upto 60 minutes to appear, so wait for the automatic update or manually check an hour or two later. Thanks :)

**Comment by johannes87** [comment]
@plibither8 Amazing, thank you :-). No worries for the dalay!
