### ISSUE TITLE
V19.7.1 (2019-07-01) has erased my markdown page

### ISSUE THREAD

**Issue by kseistrup** [plibither8/markdown-new-tab#29]
V19.7.1 (2019-07-01) has erased my markdown page: Opening a new tab simply gives me a blank page with the options of editing. All my old markdown with links has been lost.

**Comment by kseistrup** [comment]
PS: The extension auto-updated itself while chromium was open. The update doesn't recognize the markdown I had. :unamused:

**Comment by plibither8** [comment]
Hi, I am extremely sorry - but rest assured that your saved data is _still_ saved.

An erroneously and buggy version of the extension was published me, which I have quickly catered for. Version 19.7.1.1627 has fixed the error, and soon, once it is active on the Chrome Webstore, it will auto-update (or better still, you can manually update it).

Thanks a lot for your patience and sorry once again!

**Comment by plibither8** [comment]
> The update doesn't recognize the markdown I had

I'm sorry I didn't quite get this - could you elaborate?

**Comment by plibither8** [comment]
Hi! The updated version has been published - you can got to `chrome://extensions` and manually update to the new, fixed version.

**Comment by kseistrup** [comment]
I had a markdown page with lots of of links. I was working in the browser immediately before the update. I didn't notice the update itself, but I opened a new tab and found all my links were gone and all I had was a blank page.

You are saying that my old page will re-appear once the extension has been updated again?

**Comment by plibither8** [comment]
> You are saying that my old page will re-appear once the extension has been updated again?

Yes, nothing that was stored in your Chrome Sync has been deleted.

**Comment by kseistrup** [comment]
I updated the extension and now my old markdown is back. I'm a happy man again. Thanks! :smile_cat:

**Comment by plibither8** [comment]
Great to hear that, cheers :smile:!
