### ISSUE TITLE
Feature Request: Firefox Support

### ISSUE THREAD

**Issue by insanity54** [plibither8/markdown-new-tab#3]
I saw this project on Hacker News and it appealed to my interest. Unfortunately I use Firefox. It would be super cool to have a Firefox plugin that does this.

**Comment by jorgeyp** [comment]
This extension is already compatible with Firefox, I just tried loading it in Firefox Dev and seems to work fine 😄 
@plibither8 I think you can just publish it as it is and it should work!

**Comment by JohnKacz** [comment]
Hmm then maybe a pull request to add installation instructions to the README?

I'm not seeing it in Mozilla's extensions store.

**Comment by jorgeyp** [comment]
I just tested with the [debugging options](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox) in Dev edition. To install it permanently it needs to get [published](https://developer.mozilla.org/en-US/Add-ons/Distribution).

**Comment by plibither8** [comment]
@jorgeyp Sure, I too was thinking about it since its now gained quite some popularity. If and when I find time, I'll publish it to the Mozilla Extension Store. Till then, as suggested by @JohnKacz, if you could create a PR to add instructions for adding it *temporarily* (if that's a possibility, something like 'Developer Mode' in Google Chrome's extensions page) and enable it.

And till then, I've uploaded the site to https://mdnt.surge.sh. You could maybe make that the default page?

**Comment by potch** [comment]
@plibither8 howdy, I work with the add-ons team at Mozilla- we have a short [porting article](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension) on MDN about the process of packaging a chrome extension for Firefox. Let me know if there's anything I can do to help get this on our extensions directory!

**Comment by jorgeyp** [comment]
@plibither8 I added the instructions to the README #7

**Comment by tonytamps** [comment]
If you are going to publish it to the Mozilla Extension Store can I suggest some thought going into the Firefox Containers setup? 

Some people like the start page data to be saved to each container. Other like it to be shared.

**Comment by plibither8** [comment]
I'm sorry I don't quite understand what you mean by 'container'. This is
probably a Firefox-exclusive feature and so I'll read about it. If you know
of a possible implementation, feel free to create a PR :smile:

**Comment by plibither8** [comment]
Hey @tonytamps! Just checking in, how's the work going about?

**Comment by tonytamps** [comment]
Got busy, still plan on having a run at it. No hurry, right?

**Comment by andmib** [comment]
@plibither8 I've recently switched to Firefox and not having this extension be persistent in Firefox (dev workaround doesn't stay that way) is killer. Would also *love* to have sync, similar to the chrome extension. If there's anything I can do to help expedite (would be happy to donate a small amount), please let me know! Unfortunately I don't think I could help much on the coding front.

**Comment by tgrrr** [comment]
I'm testing in Chrome (multiple profiles) and Firefox. 

In the README.md, it says:
> Upcoming
>    Sync notes, revision history and settings between all Chrome browsers you are logged into

Could you please sync it with Firefox as well

**Comment by plibither8** [comment]
Hey Phil,

I'll work on the MDNT's Firefox add on this weekend, thanks for reminding
me about it. I'll make sure to implement sync in FF too.

Cheers!

**Comment by tgrrr** [comment]
Thanks!

**Comment by plibither8** [comment]
Hi everyone!

I have (finally, apologies for the super huge delay :| ) published MDNT for Firefox. You can get it here: https://addons.mozilla.org/en-US/firefox/addon/markdown-new-tab/

Thanks a lot for your patience - it was made by me during my study-breaks and free time. If you like and have enjoyed it, please consider donating a small amount (any amount will be really appreciated!) to support and sustain its development. Thank you!

[![Donate](https://img.shields.io/badge/donate-PayPal-blue.svg?style=for-the-badge&logo=paypal)](https://paypal.me/plibither8)

[![Buy Me A Coffee](https://www.buymeacoffee.com/assets/img/custom_images/purple_img.png)](https://www.buymeacoffee.com/plibither8)
