### ISSUE TITLE
Regarding the markdown reference in the docs

### ISSUE THREAD

**Issue by sandebert** [plibither8/markdown-new-tab#30]
The docs are currently linked to a markdown reference that doesn't explain things like checkboxes, etc. So I suppose it might make sense, as we seem to be using GitHub flavoured markdown, to instead link to https://github.github.com/gfm/?

**Comment by plibither8** [comment]
Thanks a lot for this :smile:! Updated the Readme: https://github.com/plibither8/markdown-new-tab/commit/8cca625ef01c93c43b5b5b194f2141866a18d632
