### ISSUE TITLE
Datetime format in bottom of window is very confusing...

### ISSUE THREAD

**Issue by sandebert** [plibither8/markdown-new-tab#31]
...as that's not even remotely like the standard around where i live.

Would it be possible to make the date format a setting? (I would obviously have no problem at all with the default format being identical to what it is now, so that current users wouldn't get surprised by a change.)

**Comment by plibither8** [comment]
Ah yes, I've just realised this, thanks for pointing it out.

Could I ask what format you use? Is it mm/dd/yyyy?

**Comment by plibither8** [comment]
I'm shifting to using `Date.toLocaleDateString()` and `Date.toLocaleTimeString()` for the date and time.

I don't think there would be any confusion caused by localising the date formats, but thanks for the concern! I'll probably add this in the settings in a later itteration :)

**Comment by sandebert** [comment]
Not even close. :smile: 

We're using [the ISO 8601 standard](https://en.wikipedia.org/wiki/ISO_8601), which boils down to yyyy-mm-dd (large-to-small order). So for me it would mean that it would show "2019-07-03 - 09:34:55" at the moment.

I imagine you're considering adding a dropdown where the user can pick one of your pre-defined formats? I can certainly understand the temptation, but in my experience that rarely matches all use-cases. Hence my suggestion to just let the user enter their own format. 

As I understand it, javascript doesn't have something like the [php date formatting](https://www.php.net/manual/en/function.date.php) built-in. But if there is a small lib for you to use, perhaps something like that could be possible? I imagine that some users would even like the datetime to simply say something like "Wednesday 5th, 11:07". (Because most of us already know the year and month without having to read it somewhere :smile:, and most of us don't care what second it is at the moment.)

One final note: You can't rely on the locale of the browser for deciding the formatting. My entire OS and browser is English, but I'm absolutely not using English formatting for dates, currencies, etc. (You would be surprised how common this is.)

**Comment by plibither8** [comment]
You learn something every day!

Thanks a lot for this piece of information &ndash; I was certainly thinking about using a dropdown-type mechanism. :sweat_smile:

I've found an npm package (https://www.npmjs.com/package/dateformat) that is very liberal and allows flexible, user-defined date formatting. I hope this will be enough to bring the required flexibility a general user might require. Something like "Wednesday 5th, 11:07" can be formatted by sing using this string: `dddd dS, HH:MM`.

**Comment by sandebert** [comment]
That package looks pretty much perfect, as far as I can tell. :smile:

**Comment by plibither8** [comment]
Great, I'll release the update soon and notify you :)

**Comment by sandebert** [comment]
You da man! :+1: 

As for learning something every day, have a look at this [curated list of awesome falsehoods programmers believe in](https://github.com/kdeldycke/awesome-falsehood). (And make sure to not miss the [article about names](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/) that started this kind of lists - it will make your head hurt.)

**Comment by plibither8** [comment]
This is beautiful &ndash; starred! Thanks for sharing :smile:

**Comment by plibither8** [comment]
Hey Fredrik, 

The update for Firefox is live and has been published. The Chrome update will too be published soon (in max. 60 minutes) - it's "pending review" right now.

**Comment by sandebert** [comment]
Chrome store shows 19.7.2, but I got the 19.7.3 when I updated in my browser, so it's already out there. Very well done! :gift: 

A small note:
When I try it, the field says "undefined". If I save that, this is displayed:
![image](https://user-images.githubusercontent.com/3855726/60581289-d1a5e700-9d86-11e9-98f7-777cc953bb25.png)

It's not a big deal for me, but for the benefit of your other users I would recommend setting your previous format as default value. Just so you don't get curious people clicking that button and then wondering what happened to their date. :smile:

**Comment by plibither8** [comment]
Argh, I should have tested everything before pushing the changes.

Nevertheless, I've corrected the bug and published a newer version (https://github.com/plibither8/markdown-new-tab/releases/tag/19.7.3.948) that should fix this.

Thanks a lot for bringing it up :)

**Comment by plibither8** [comment]
PS. Thank you (I guess you know what for ☺️)
