### ISSUE TITLE
Possiblity to have bookmark bar

### ISSUE THREAD

**Issue by PavlikPolivka** [plibither8/markdown-new-tab#32]
Hi. 

I love the idea of this, but my workflow is that I have the bookmark bar hidden and only visible on New Tab. With this extension the bookmark bar is not visible there. 

Is this something that can even be done? 

Thanks.

**Comment by plibither8** [comment]
Hello :wave:,

I looked up possible solutions, but nothing works. This is probably a browser thing and no webextension API allows for controlling the visibility of the bookmarks bar. I might not be completely aware of your workflow, but maybe try to copy/paste your bookmarks directly into Markdown New Tab?

Thanks for opening the issue and let me know of anything else :)

Cheers!
