### ISSUE TITLE
time/date

### ISSUE THREAD

**Issue by atomGit** [plibither8/markdown-new-tab#34]
the time/date and last edited functions aren't helpful IMO - the clock time is not accurate for me anyway - i thought this had to do with `privacy.resistFingerprinting` but apparently not - also, don't most people have a taskbar with time/date? - i think that space would be better used for notes - the settings icon could then be positioned below the edit icon maybe

i see some CSS options are planned - i might suggest an option to set the max-width also, or just a text control where people can add whatever CSS they want

other than that i really like it

**Comment by plibither8** [comment]
> i might suggest an option to set the max-width also, or just a text control where people can add whatever CSS they want

This is great. I think I'll add this soon, whenever I get time next. This way you can `display: none` the Time and date too. What say?

**Comment by atomGit** [comment]
that'll work
personally i would drop those features as i don't see the need for them, but it's you're ball game and i respect that :)

given that you intend to allow user CSS, i'm going to make my own theme and will be happy to share it here if you wish so others can use it or whatever

**Comment by plibither8** [comment]
That's great, if love to see your theme! :)

Thanks!

**Comment by atomGit** [comment]
just a quickie that suites my needs - obviously if one is saving revisions they won't want to hide `section.bar #lastEdited`

```
@-moz-document url("moz-extension://090515c1-9ac8-425b-b561-d6f11fae9a4a/index.html") {
    html, body, :root {
        background: #212121 !important;
        font-family: unset !important;
        scrollbar-color: #595959 #a6a6a6; /* works in FF, i don't know about Chrome */
    }
    .markdown-body {
        max-width: 1250px !important;
        color: #e0e0e0 !important;
    }
    section.bar {
        border-top: none !important;
        background: transparent !important;
    }
    section.bar #time {
        display: none !important;
    }
    section.bar #lastEdited {
        display: none !important;
    }
}
```

**Comment by plibither8** [comment]
The Firefox add-on has been updated, Chrome will too soon be updated. Thanks for bringing this issue up :)
