### ISSUE TITLE
GitHub Flavored Markdown

### ISSUE THREAD

**Issue by formido** [plibither8/markdown-new-tab#5]
I edit READMEs in GitHub all day, so it'd be cool if you had an extension for the GH flavor of Markdown.

**Comment by plibither8** [comment]
Hi! The current flavor set to the converter is of GitHub. If there is anything that is being mis-rendered, please let me know. Thanks!

**Comment by formido** [comment]
Oh, I was fooled cos it doesn't seem to do syntax highlighting.

**Comment by plibither8** [comment]
Yes, that is one think I too realised. I'll try to find a solution, thanks
for reminding me :smile:

**Comment by formido** [comment]
No worries. Syntax highlighting isn't too important for estimating how the README will look. If it's otherwise GHFM, that's awesome and perfect for my uses! 💯

**Comment by plibither8** [comment]
Awesome :)
