### ISSUE TITLE
One button active in a view

### ISSUE THREAD

**Issue by broxmen** [plibither8/markdown-new-tab#6]
Hey Mihir! Love the concept.
Currently the default view has 2 buttons edit and save.
In the view mode save button isn't needed and in edit mode save button isn't needed.

So ideally you would need only a single button to function at a time the placement of which is entirely up to you!

**Comment by plibither8** [comment]
Hey! I didn't think about this up until now and it seems like a good point. I'll implement as soon as I get time. Thanks!
