### ISSUE TITLE
Feature Request: Sync Notes Between Instances

### ISSUE THREAD

**Issue by emsenn** [plibither8/markdown-new-tab#8]
Dan Eden's [Lucid](https://github.com/daneden/chrome-lucid) program somehow syncs your notes between different Chromes you're running - in my case, my laptop and desktop.

I'd love to see something similar here.

**Comment by plibither8** [comment]
Hi @emsenn,

Seems like a good idea. How about uploading the data to a secret gist?

**Comment by emsenn** [comment]
That's a clever solution to that!

My one concern is that it would require an account a user might not have, whereas however Lucid does it, you don't need to do anything to set it up.

That said, I would **prefer** it be done with gists (or even better, [Gitlab snippets](https://docs.gitlab.com/ee/user/snippets.html) - it'd let me potentially set up some sort of CI/CD between my new-tab notes and my [homepage](https://emsenn.net), which would be... just truly an amazing addition to my workflow I hadn't ever really thought of.

**Comment by ahmetb** [comment]
> As of Chrome 20 and above you can use [chrome.storage](http://code.google.com/chrome/extensions/storage.html) module to save to the cloud.

from: https://stackoverflow.com/questions/4901024/how-to-synchronize-chrome-extension-data-on-different-computers

**Comment by plibither8** [comment]
@ahmetb Beautiful! This has to be the neatest and most stable solution. I guess I'll go ahead with it. @emsenn Thoughts?

**Comment by plibither8** [comment]
Thanks to @denel-manilov, we now have sync support (#19)!

**Comment by plibither8** [comment]
Apologies for the delay, the new version is up on the webstore now.
